Repository dimagi/commcare-core, pull requests merged in 2018-03, with the labels that each got.

#779 Add common hashtags to ignore-set
  src/main/java/org/javarosa/xform/parse/XFormParser.java
Labels: product/invisible

#778 Fixing getEntriesForCommand
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/suite/model/MenuLoader.java
  src/main/java/org/commcare/suite/model/Suite.java
  src/main/java/org/commcare/util/CommCarePlatform.java
  src/test/java/org/commcare/backend/session/test/ChildModuleNavigationTests.java
  src/test/resources/app_with_child_modules/modules-0/forms-0.xml
  src/test/resources/app_with_child_modules/modules-1/forms-0.xml
  src/test/resources/app_with_child_modules/profile.ccpr
  src/test/resources/app_with_child_modules/suite.xml
  src/test/resources/app_with_child_modules/user_restore.xml
Labels: bug, minor (quick review), product/invisible, ready for review

#768 Adds RequirementType for UnfullfilledRequirementException
  src/main/java/org/commcare/xml/CommCareElementParser.java
  src/main/java/org/commcare/xml/ProfileParser.java
  src/main/java/org/javarosa/xml/util/UnfullfilledRequirementsException.java
Labels: cross requested, enhancement, product/invisible, ready for review

#780 fix test
  src/test/java/org/javarosa/core/model/test/FormDefTest.java
  src/test/resources/xform_tests/test_question_level_actions.xml
Labels: minor (quick review), product/invisible, ready for review

#775 Add concept of training root menu
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/main/java/org/commcare/suite/model/Menu.java
  src/main/java/org/commcare/suite/model/MenuLoader.java
  src/test/java/org/commcare/backend/suite/model/test/EmptyAppElementsTests.java
Labels: cross requested, product/invisible, ready for review

#781 Only log exception with DetailFeild once
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
Labels: product/invisible

#782 Only log exception with DetailFeild once
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
Labels: product/invisible
