Repository dimagi/commcare-core, pull requests merged in 2018-11, with the labels that each got.

#829 Update nodeset error text
  src/main/java/org/javarosa/xpath/expr/XPathCountFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathSumFunc.java
Labels: minor (quick review), product/all-users

#828 Adds a function to identify version mismatch
  src/main/java/org/javarosa/xml/util/UnfullfilledRequirementsException.java
Labels: minor (quick review), product/invisible, ready for review

#830 Temporary Fix for Improper Case Sync Algorithm
  src/main/java/org/commcare/cases/util/CasePurgeFilter.java
  src/test/resources/case_relationship_tests.json
Labels: bug, product/invisible, ready for review

#831 [LTS Port] Reach case ownership Issue
  src/main/java/org/commcare/cases/util/CasePurgeFilter.java
  src/test/resources/case_relationship_tests.json
Labels: product/invisible

#832 Adds provision to disable retry in network requests
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
Labels: minor (quick review), product/invisible, ready for review
