Repository dimagi/commcare-core, pull requests merged in 2018-02, with the labels that each got.

#749 updates to okHttp 3.9.1
  build.gradle
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
Labels: minor (quick review), product/invisible

#744 Improve error message when sorting on an empty list
  src/main/java/org/javarosa/xpath/expr/XPathSortByFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathSortFunc.java
Labels: product/invisible

#746 Implementing app fixture handling for CommCareInstanceInitializer
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
  src/cli/java/org/commcare/util/mocks/CLIInstanceInitializer.java
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/commcare/core/sandbox/SandboxUtils.java
  src/main/java/org/commcare/util/CommCarePlatform.java
  src/main/java/org/javarosa/core/services/storage/StorageManager.java
  src/main/java/org/javarosa/core/services/storage/util/DummyIndexedStorageUtility.java
  src/translate/java/org/javarosa/engine/XFormPlayer.java
Labels: product/invisible

#752 Split out FormInstanceLoader functionality
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/translate/java/org/javarosa/xform/schema/FormInstanceLoader.java
Labels: minor (quick review), product/invisible

#753 Formplayer 2.42
  build.gradle
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/cli/java/org/commcare/util/screen/SessionUtils.java
  src/cli/java/org/commcare/util/screen/SyncScreen.java
  src/main/java/org/commcare/core/graph/model/GraphData.java
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
  src/main/java/org/commcare/resources/model/installers/ProfileInstaller.java
  src/main/java/org/commcare/suite/model/Menu.java
  src/main/java/org/commcare/suite/model/StackFrameStep.java
  src/main/java/org/commcare/util/CommCarePlatform.java
  src/main/java/org/javarosa/form/api/FormEntryController.java
  src/main/java/org/javarosa/xpath/expr/XPathSortByFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathSortFunc.java
  src/test/java/org/cli/CliTests.java
  src/test/resources/basic_app/basic.ccz
  src/test/resources/basic_app/restore.xml
  src/translate/java/org/javarosa/engine/XFormPlayer.java
Labels: product/invisible

#754 2.42 Formplayer Backmerge Backmerge
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: product/invisible

#755 Increment CommCareConfigEngine version to 2.42
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
Labels: product/invisible

#751 Add "Single Load" event for Performance Traces
  src/main/java/org/commcare/cases/instance/IndexedFixtureChildElement.java
Labels: product/invisible, ready for review

#757 Add LocalizerManager class
  src/main/java/org/javarosa/core/services/locale/Localization.java
  src/main/java/org/javarosa/core/services/locale/LocalizerManager.java
Labels: product/invisible

#759 Move EntityStringFilterer into Formplayer
  src/main/java/org/commcare/cases/entity/EntityStringFilterer.java
Labels: minor (quick review), product/invisible

#761 ReferenceManager refactor
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
  src/main/java/org/commcare/modern/reference/ArchiveFileRoot.java
  src/main/java/org/commcare/resources/model/ResourceTable.java
  src/main/java/org/commcare/resources/model/installers/InstallerUtil.java
  src/main/java/org/commcare/resources/model/installers/LocaleFileInstaller.java
  src/main/java/org/commcare/suite/model/Detail.java
  src/main/java/org/commcare/suite/model/OfflineUserRestore.java
  src/main/java/org/javarosa/core/reference/PrefixedRootFactory.java
  src/main/java/org/javarosa/core/reference/ReferenceDataSource.java
  src/main/java/org/javarosa/core/reference/ReferenceHandler.java
  src/main/java/org/javarosa/core/reference/ReferenceManager.java
  src/main/java/org/javarosa/core/reference/RootTranslator.java
  src/test/java/org/commcare/util/reference/test/JavaResourceReferenceTest.java
  src/test/java/org/javarosa/core/model/test/QuestionDefTest.java
Labels: product/invisible

#765 ReferenceHandler
  src/main/java/org/commcare/suite/model/Detail.java
  src/main/java/org/javarosa/core/reference/ReferenceHandler.java
  src/main/java/org/javarosa/core/reference/ReferenceManager.java
  src/test/java/org/commcare/util/reference/test/JavaResourceReferenceTest.java
Labels: product/invisible

#766 Use ReferenceManager.instance() instead of ReferenceHandler
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
  src/main/java/org/commcare/modern/reference/ArchiveFileRoot.java
  src/main/java/org/commcare/resources/model/ResourceTable.java
  src/main/java/org/commcare/resources/model/installers/InstallerUtil.java
  src/main/java/org/commcare/resources/model/installers/LocaleFileInstaller.java
  src/main/java/org/commcare/suite/model/Detail.java
  src/main/java/org/commcare/suite/model/OfflineUserRestore.java
  src/main/java/org/javarosa/core/reference/PrefixedRootFactory.java
  src/main/java/org/javarosa/core/reference/ReferenceDataSource.java
  src/main/java/org/javarosa/core/reference/ReferenceManager.java
  src/main/java/org/javarosa/core/reference/RootTranslator.java
  src/test/java/org/commcare/util/reference/test/JavaResourceReferenceTest.java
  src/test/java/org/javarosa/core/model/test/QuestionDefTest.java
Labels: product/invisible

#767 Remove unused variable
  src/main/java/org/javarosa/core/reference/ReferenceManager.java
Labels: minor (quick review), product/invisible

#745 Allow setting a new Installer to a Resource for Android DB upgradation
  src/main/java/org/commcare/resources/model/Resource.java
Labels: cross requested, product/invisible

#763 Restore SuiteParser to as in master
  src/main/java/org/commcare/xml/SuiteParser.java
  src/test/java/org/commcare/backend/suite/model/test/AppStructureTests.java
Labels: product/invisible

#748 Refactor ExtWrapList to be usable for any implementing class of List
  src/main/java/org/javarosa/core/util/externalizable/ExtWrapList.java
Labels: cross requested, enhancement, minor (quick review), product/invisible

#769 Adds form info in log for Non-Question object
  src/main/java/org/javarosa/form/api/FormEntryModel.java
Labels: minor (quick review), product/invisible

#756 Only create index if not exists
  src/main/java/org/commcare/modern/database/DatabaseIndexingUtils.java
Labels: product/invisible

#760 Add LocalizerManager class
  src/main/java/org/javarosa/core/services/locale/Localization.java
  src/main/java/org/javarosa/core/services/locale/LocalizerManager.java
Labels: product/invisible

#764 Split non-DB centric sorting into commcare-core utility
  src/main/java/org/commcare/util/EntityProvider.java
  src/main/java/org/commcare/util/EntitySortUtil.java
Labels: product/invisible

#732 Remove rulesList from PropertyManager
  src/main/java/org/javarosa/core/services/PropertyManager.java
Labels: product/invisible

#770 Remove rulesList from PropertyManager
  src/main/java/org/javarosa/core/services/PropertyManager.java
Labels: minor (quick review), product/invisible

#771 Query screen should return True for success
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: product/invisible

#758 Update XPathExpression isLeafNode
  src/main/java/org/javarosa/xpath/expr/XPathExpression.java
Labels: minor (quick review), product/invisible

#773 Remove verbose XFormParser logs
  src/main/java/org/javarosa/xform/parse/XFormParser.java
Labels: product/invisible

#774 Revert removing EntityDatum instanceof check from guessUnknown
  src/main/java/org/commcare/session/CommCareSession.java
Labels: product/invisible

#776 break out regex tests and add a few more
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: product/invisible

#777 Master regex
  build.gradle
  lib/regexp-me.jar
  src/main/java/org/javarosa/xpath/expr/XPathRegexFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathReplaceFunc.java
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: product/invisible
