Repository dimagi/commcare-core, pull requests merged in 2018-06, with the labels that each got.

#810 Fixes ClassCastException ViewEntry can't be cast to FormEntry
  src/main/java/org/commcare/session/CommCareSession.java
Labels: minor (quick review), product/invisible, ready for review

#812 Make sure childrenMap is not null
  src/main/java/org/javarosa/core/util/ShortestCycleAlgorithm.java
Labels: product/invisible

#811 Adds data change log type for Device Logs
  src/main/java/org/commcare/util/LogTypes.java
Labels: cross requested, minor (quick review), product/invisible

#813 Check if select() arg is valid quesiton
  src/main/java/org/javarosa/xpath/expr/XPathSelectedFunc.java
Labels: product/invisible

#809 Add ResourceInitializationException for use when resource init fails
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/cli/CliCommand.java
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
  src/main/java/org/commcare/resources/ResourceManager.java
  src/main/java/org/commcare/resources/model/ResourceInitializationException.java
  src/main/java/org/commcare/resources/model/ResourceInstaller.java
  src/main/java/org/commcare/resources/model/ResourceTable.java
  src/main/java/org/commcare/resources/model/installers/BasicInstaller.java
  src/main/java/org/commcare/resources/model/installers/CacheInstaller.java
  src/main/java/org/commcare/resources/model/installers/LocaleFileInstaller.java
  src/main/java/org/commcare/resources/model/installers/LoginImageInstaller.java
  src/main/java/org/commcare/resources/model/installers/OfflineUserRestoreInstaller.java
  src/main/java/org/commcare/resources/model/installers/ProfileInstaller.java
  src/main/java/org/commcare/resources/model/installers/SuiteInstaller.java
  src/main/java/org/commcare/util/CommCarePlatform.java
Labels: bug, cross requested, product/invisible, ready for review

#808 Fixes crash in checksum caused by negative index value
  src/main/java/org/javarosa/xpath/expr/XPathChecksumFunc.java
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: bug, minor (quick review), product/all-users, ready for review

#807 Adds Drift Interceptor
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/commcare/core/services/CommCarePreferenceManagerFactory.java
  src/main/java/org/commcare/core/services/ICommCarePreferenceManager.java
  src/main/java/org/commcare/session/SessionInstanceBuilder.java
  src/main/java/org/javarosa/core/model/utils/DateUtils.java
Labels: cross requested, product/invisible, ready for review

#814 Add external_id as indexable case property
  src/main/java/org/commcare/cases/instance/CaseChildElement.java
  src/main/java/org/commcare/cases/instance/CaseInstanceTreeElement.java
  src/main/java/org/commcare/cases/model/Case.java
  src/main/java/org/commcare/xml/CaseXmlParser.java
  src/main/java/org/commcare/xml/bulk/BulkProcessingCaseXmlParser.java
  src/main/resources/casedb_instance_structure.xml
  src/test/java/org/commcare/cases/test/CaseExternalIdTest.java
  src/test/resources/case_create_external_id.xml
  src/test/resources/empty_restore.xml
Labels: product/invisible

#716 Caching of expressions in forms
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
  src/cli/java/org/commcare/util/screen/ScreenUtils.java
  src/main/java/org/commcare/cases/entity/NodeEntityFactory.java
  src/main/java/org/commcare/suite/model/MenuLoader.java
  src/main/java/org/commcare/suite/model/Text.java
  src/main/java/org/javarosa/core/model/FormDef.java
  src/main/java/org/javarosa/core/model/condition/EvaluationContext.java
  src/main/java/org/javarosa/core/model/instance/TreeReference.java
  src/main/java/org/javarosa/core/model/instance/utils/TreeUtilities.java
  src/main/java/org/javarosa/core/model/trace/AccumulatingReporter.java
  src/main/java/org/javarosa/core/model/trace/BulkEvaluationTrace.java
  src/main/java/org/javarosa/core/model/trace/EvaluationTrace.java
  src/main/java/org/javarosa/core/model/trace/EvaluationTraceReduction.java
  src/main/java/org/javarosa/core/model/trace/EvaluationTraceReporter.java
  src/main/java/org/javarosa/core/model/trace/EvaluationTraceSerializer.java
  src/main/java/org/javarosa/core/model/trace/ReducingTraceReporter.java
  src/main/java/org/javarosa/core/model/trace/StringEvaluationTraceSerializer.java
  src/main/java/org/javarosa/core/model/trace/TraceSerialization.java
  src/main/java/org/javarosa/core/model/utils/InstrumentationUtils.java
  src/main/java/org/javarosa/form/api/FormEntryModel.java
  src/main/java/org/javarosa/xpath/XPathConditional.java
  src/main/java/org/javarosa/xpath/analysis/AnalysisInvalidException.java
  src/main/java/org/javarosa/xpath/analysis/ContainsUncacheableExpressionAnalyzer.java
  src/main/java/org/javarosa/xpath/analysis/InstanceNameAccumulatingAnalyzer.java
  src/main/java/org/javarosa/xpath/analysis/ReferencesMainInstanceAnalyzer.java
  src/main/java/org/javarosa/xpath/analysis/TopLevelContextTypesAnalyzer.java
  src/main/java/org/javarosa/xpath/analysis/TreeReferenceAccumulatingAnalyzer.java
  src/main/java/org/javarosa/xpath/analysis/XPathAccumulatingAnalyzer.java
  src/main/java/org/javarosa/xpath/analysis/XPathAnalyzer.java
  src/main/java/org/javarosa/xpath/analysis/XPathBooleanAnalyzer.java
  src/main/java/org/javarosa/xpath/expr/CacheableExprState.java
  src/main/java/org/javarosa/xpath/expr/ExpressionCacheKey.java
  src/main/java/org/javarosa/xpath/expr/ExpressionCacher.java
  src/main/java/org/javarosa/xpath/expr/InFormCacheableExpr.java
  src/main/java/org/javarosa/xpath/expr/VolatileXPathFuncExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathArithExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathBinaryOpExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathBoolExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathCmpExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathCustomRuntimeFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathDependFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathEqExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathExpression.java
  src/main/java/org/javarosa/xpath/expr/XPathFilterExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathNowFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathNumNegExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathNumericLiteral.java
  src/main/java/org/javarosa/xpath/expr/XPathPathExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathRandomFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathSleepFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathStringLiteral.java
  src/main/java/org/javarosa/xpath/expr/XPathTodayFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathUnaryOpExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathUnionExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathUuidFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathVariableReference.java
  src/test/java/org/javarosa/xpath/analysis/test/StaticAnalysisTest.java
  src/translate/java/org/javarosa/engine/XFormPlayer.java
Labels: cross requested, product/invisible, ready for review

#816 LINTER Run Remove Redundant Casts
  src/main/java/org/javarosa/xform/parse/XFormParser.java
  src/main/java/org/javarosa/xform/util/XFormAnswerDataSerializer.java
  src/main/java/org/javarosa/xpath/expr/XPathExpression.java
  src/test/java/org/javarosa/core/model/data/test/SelectMultiDataTests.java
Labels: product/invisible
