Repository dimagi/commcare-core, pull requests merged in 2018-05, with the labels that each got.

#788 Device log cleaning
  src/main/java/org/commcare/resources/ResourceManager.java
  src/main/java/org/commcare/resources/model/ResourceTable.java
  src/main/java/org/commcare/resources/model/installers/ProfileInstaller.java
  src/main/java/org/commcare/util/LogTypes.java
  src/main/java/org/javarosa/core/services/Logger.java
  src/main/java/org/javarosa/xpath/expr/XPathExpression.java
Labels: cross requested, product/invisible, ready for review

#799 Backmerge 2.43
  src/main/java/org/commcare/session/CommCareSession.java
  src/test/java/org/commcare/backend/session/test/ChildModuleNavigationTests.java
Labels: product/invisible

#798 Combobox tweaks for inddex
  src/main/java/org/commcare/cases/util/StringUtils.java
  src/main/java/org/javarosa/core/model/FuzzyMatchFilterRule.java
Labels: minor (quick review), product/custom, ready for review

#772 Formplayer update to 2.43
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
  src/cli/java/org/commcare/util/mocks/MockUserDataSandbox.java
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/main/java/org/commcare/cases/instance/IndexedFixtureChildElement.java
  src/main/java/org/commcare/core/interfaces/UserSandbox.java
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/commcare/resources/model/Resource.java
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/session/SessionInstanceBuilder.java
  src/main/java/org/commcare/suite/model/Menu.java
  src/main/java/org/commcare/suite/model/MenuLoader.java
  src/main/java/org/commcare/suite/model/Suite.java
  src/main/java/org/commcare/util/CommCarePlatform.java
  src/main/java/org/commcare/util/EntityProvider.java
  src/main/java/org/commcare/util/EntitySortUtil.java
  src/main/java/org/commcare/xml/CommCareElementParser.java
  src/main/java/org/commcare/xml/ProfileParser.java
  src/main/java/org/javarosa/core/util/externalizable/ExtWrapList.java
  src/main/java/org/javarosa/form/api/FormEntryModel.java
  src/main/java/org/javarosa/xform/parse/XFormParser.java
  src/main/java/org/javarosa/xml/util/UnfullfilledRequirementsException.java
  src/test/java/org/commcare/backend/session/test/ChildModuleNavigationTests.java
  src/test/java/org/commcare/backend/suite/model/test/EmptyAppElementsTests.java
  src/test/java/org/javarosa/core/model/test/FormDefTest.java
  src/test/resources/app_with_child_modules/modules-0/forms-0.xml
  src/test/resources/app_with_child_modules/modules-1/forms-0.xml
  src/test/resources/app_with_child_modules/profile.ccpr
  src/test/resources/app_with_child_modules/suite.xml
  src/test/resources/app_with_child_modules/user_restore.xml
  src/test/resources/xform_tests/test_question_level_actions.xml
Labels: product/invisible

#801 Bump source compatibility to 1.8
  build.gradle
Labels: product/invisible

#804 Remove unused concept
  src/main/java/org/javarosa/form/api/FormController.java
Labels: cross requested, minor (quick review), product/invisible, ready for review

#796 Adds Parsing logic for Update Info Forms
  src/main/java/org/commcare/resources/model/InstallerFactory.java
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/xml/SuiteParser.java
Labels: cross requested, product/internal-or-flagged, ready for review

#805 Adds back missing function wrongly removed during conflicts resolution
  src/main/java/org/commcare/session/CommCareSession.java
Labels: minor (quick review), product/invisible, ready for review
