Repository dimagi/commcare-core, pull requests merged in 2018-04, with the labels that each got.

#785 Enable app updates for Formplayer
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
Labels: product/invisible

#786 Pull error handling from CommCareConfigEngine to Application Host
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
Labels: product/invisible

#789 manually fix minor version getting behind
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
Labels: product/invisible

#793 2.43 - Fix multiplicity of children in session instance
  src/main/java/org/commcare/session/SessionInstanceBuilder.java
Labels: bug, minor (quick review), product/invisible, ready for review

#792 Fix multiplicity of children in session instance
  src/main/java/org/commcare/session/SessionInstanceBuilder.java
  src/main/java/org/javarosa/core/model/condition/EvaluationContext.java
  src/translate/java/org/javarosa/engine/xml/TreeElementParser.java
Labels: bug, critical-bug-fix, minor (quick review), product/invisible, ready for review

#791 Creates no auth service for Ping request to Commcare
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
Labels: cross requested, product/invisible, ready for review

#790 Removes deprecated classesdir when building with Android Gradle Plugin 3.0.1
  build.gradle
Labels: cross requested, product/invisible, ready for review

#795 Correct error message
  src/main/java/org/javarosa/core/model/data/IntegerData.java
Labels: product/invisible
