Repository dimagi/commcare-core, pull requests merged in 2019-04, with the labels that each got.

#849 Replaced ex type from IllegalArgumentEx to XPathEx
  src/main/java/org/javarosa/core/model/data/helper/Selection.java
Labels: minor (quick review), product/all-users, ready for review

#851 Fix for Short Cycle Detection Algorithm
  src/main/java/org/javarosa/core/util/ShortestCycleAlgorithm.java
  src/main/java/org/javarosa/xform/parse/XFormParser.java
  src/test/java/org/javarosa/core/model/test/CyclicReferenceTests.java
  src/test/resources/xform_tests/real_form_with_cycle_errors.xml
Labels: bug, product/all-users

#848 added error context for XPathConditional
  src/main/java/org/javarosa/xpath/XPathConditional.java
  src/main/java/org/javarosa/xpath/expr/XPathPathExpr.java
  src/main/java/org/javarosa/xpath/expr/XPathStep.java
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: minor (quick review), product/all-users, ready for review

#853 Updated cyclical message error text for clarity
  src/main/java/org/javarosa/core/util/ShortestCycleAlgorithm.java
  src/test/java/org/javarosa/core/model/test/CyclicReferenceTests.java
Labels: enhancement, minor (quick review), product/invisible

#852 Improve Hashing Performance
  src/main/java/org/commcare/cases/util/CaseDBUtils.java
Labels: cross requested, enhancement, minor (quick review), product/invisible

#842 Last sync support for Indexed Fixtures
  build.gradle
  src/cli/java/org/commcare/util/mocks/MockUserDataSandbox.java
  src/main/java/org/commcare/cases/instance/IndexedFixtureInstanceTreeElement.java
  src/main/java/org/commcare/cases/instance/StorageInstanceTreeElement.java
  src/main/java/org/commcare/cases/query/QuerySensitiveTreeElementWrapper.java
  src/main/java/org/commcare/core/interfaces/UserSandbox.java
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/commcare/modern/database/IndexedFixturePathsConstants.java
  src/main/java/org/commcare/xml/IndexedFixtureXmlParser.java
  src/main/java/org/javarosa/core/model/IndexedFixtureIdentifier.java
  src/main/java/org/javarosa/core/model/instance/AbstractTreeElement.java
  src/main/java/org/javarosa/core/model/instance/DataInstance.java
  src/test/java/org/commcare/fixtures/test/FixtureQueryTest.java
  src/test/resources/fixture_create.xml
  src/test/resources/indexed_fixture/indexed-fixture.xml
Labels: enhancement, product/internal-or-flagged, ready for review
