Repository dimagi/commcare-core, pull requests merged in 2019-11, with the labels that each got.

#870 Formplayer Modernization Update
  build.gradle
Labels: cross requested, don't pull, product/invisible

#869 Adds interface to get released on time from a reference
  src/main/java/org/javarosa/core/reference/ReleasedOnTimeSupportedReference.java
Labels: cross requested, product/invisible, ready for review

#872 Merge Master back into formplayer branch
  src/main/java/org/commcare/xml/bulk/BulkProcessingCaseXmlParser.java
  src/test/java/org/commcare/cases/test/CaseParseAndReadTest.java
  src/test/resources/case_create_overwrite.xml
  src/test/resources/case_create_overwrite_output.xml
Labels: product/invisible
