Repository dimagi/commcare-core, pull requests merged in 2019-02, with the labels that each got.

#838 Adds a clear api to Logger
  src/main/java/org/javarosa/core/services/Logger.java
Labels: cross requested, minor (quick review), product/invisible, ready for review

#834 Pass UnResolvedResourceExceptions during install to calling function
  src/main/java/org/commcare/resources/model/ResourceTable.java
Labels: cross requested, product/invisible, ready for review

#803 Supporting changes for recovery measures
  src/main/java/org/commcare/core/network/AuthInfo.java
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
  src/main/java/org/commcare/resources/ResourceManager.java
  src/main/java/org/commcare/resources/model/ResourceTable.java
  src/main/java/org/javarosa/core/util/externalizable/ExtUtil.java
  src/main/java/org/javarosa/xml/util/UnfullfilledRequirementsException.java
Labels: cross requested, product/custom, ready for review

#839 Logs reference in error
  src/main/java/org/javarosa/form/api/FormEntryController.java
Labels: minor (quick review), product/invisible, ready for review

#840 Fix for Broken optimization path on indexed fixtures
  src/main/java/org/commcare/cases/util/StorageBackedTreeRoot.java
  src/main/java/org/javarosa/core/model/instance/utils/FormLoadingUtils.java
  src/test/java/org/commcare/fixtures/test/IndexedFixtureTests.java
  src/test/resources/indexed-fixture-with-keys.xml
Labels: bug, product/invisible, ready for review
