Repository dimagi/commcare-core, pull requests merged in 2020-07, with the labels that each got.

#918 Have more info in SerializationLimitationException
  src/main/java/org/javarosa/core/util/externalizable/ExtUtil.java
  src/main/java/org/javarosa/core/util/externalizable/SerializationLimitationException.java
Labels: product/invisible

#919 fixes the comparison for minimal version to check for minor equality
  src/main/java/org/commcare/xml/ProfileParser.java
Labels: product/invisible

#921 Use the new KXML lib across the board to fix Emoji Issues
  build.gradle
Labels: bug, product/invisible

#920 Assorted Tests
  src/test/java/org/commcare/cases/test/BadCaseXMLTests.java
  src/test/java/org/javarosa/core/model/utils/test/LocalizerTest.java
  src/test/java/org/javarosa/xform/parse/SendParseTests.java
  src/test/java/org/javarosa/xform/parse/TextEncodingTests.java
  src/test/resources/case_parse/no_name.xml
  src/test/resources/xform_tests/itext_encoding.xml
Labels: product/invisible

#922 255 chars limit on case name, type, owner_id and external_id
  src/main/java/org/commcare/xml/CaseXmlParser.java
  src/main/java/org/javarosa/xml/util/InvalidCasePropertyLengthException.java
  src/test/java/org/commcare/cases/test/BadCaseXMLTests.java
  src/test/resources/case_parse/case_create_broken_length.xml
Labels: product/all-users, ready for review

#871 Adds and Parses buildProfileId for Profile
  src/main/java/org/commcare/suite/model/Profile.java
  src/main/java/org/commcare/xml/ProfileParser.java
Labels: cross requested, product/invisible, ready for review

#923 Enable a thread local strategy for the prototype manager
  src/main/java/org/javarosa/core/services/PrototypeManager.java
Labels: product/invisible, ready for review

#901 Add PUT method to retrofit network service
  src/main/java/org/commcare/core/network/CommCareNetworkService.java
Labels: cross requested, minor (quick review), product/invisible

#924 Improve performance for queries against missing case properties
  src/main/java/org/javarosa/core/model/instance/DataInstance.java
  src/main/java/org/javarosa/xpath/XPathLazyNodeset.java
  src/test/java/org/commcare/cases/test/CaseXPathQueryTest.java
  src/test/java/org/commcare/fixtures/test/FixtureQueryTest.java
Labels: enhancement, product/invisible
