Repository dimagi/commcare-core, pull requests merged in 2020-03, with the labels that each got.

#881 Library updates
  build.gradle
Labels: minor (quick review), product/invisible

#882 Throw exception when userid is null for a case
  src/main/java/org/commcare/xml/CaseXmlParser.java
Labels: bug, minor (quick review), product/all-users, ready for review

#883 Fix crash with missing owner_id in create case block in bulk processing
  src/main/java/org/commcare/xml/bulk/BulkProcessingCaseXmlParser.java
Labels: bug, product/invisible, ready for review

#884 Use base query contexts with CLI loads
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: enhancement, product/invisible
