Repository dimagi/commcare-core, pull requests merged in 2020-11, with the labels that each got.

#944 Add encrypt-string as an XPath function
  src/main/java/org/javarosa/xpath/expr/FunctionUtils.java
  src/main/java/org/javarosa/xpath/expr/XPathEncryptStringFunc.java
  src/main/java/org/javarosa/xpath/parser/ast/ASTNodeFunctionCall.java
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: enhancement, product/invisible

#947 Allow variable length initialization vector
  src/main/java/org/javarosa/xpath/expr/XPathEncryptStringFunc.java
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: product/invisible

#945 mark initialization
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: product/invisible

#948 update meta
  src/main/java/org/javarosa/core/services/storage/util/DummyIndexedStorageUtility.java
Labels: product/invisible

#953 Updated case claim to respect ordering of prompts
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: cross requested, product/internal-or-flagged, product/invisible

#951 Use SecureRandom instead of SecureRandom.getInstanceStrong for test
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: minor (quick review), product/invisible

#952 Case claim: stop treating no results as an error
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: product/internal-or-flagged, product/invisible
