Repository dimagi/commcare-core, pull requests merged in 2020-06, with the labels that each got.

#908 Use a separate index rather than currentFormIndex to validate constraints
  src/main/java/org/javarosa/form/api/FormController.java
  src/main/java/org/javarosa/form/api/FormEntryController.java
Labels: bug, cross requested, product/internal-or-flagged

#910 Normalize search filter before performing search
  src/main/java/org/commcare/util/EntitySortUtil.java
Labels: minor (quick review), product/all-users

#899 Adds lazy resource property
  src/main/java/org/commcare/resources/model/MissingMediaException.java
  src/main/java/org/commcare/resources/model/Resource.java
  src/main/java/org/commcare/resources/model/ResourceTable.java
  src/main/java/org/commcare/resources/model/installers/InstallerUtil.java
  src/main/java/org/commcare/resources/model/installers/LocaleFileInstaller.java
  src/main/java/org/commcare/resources/model/installers/SuiteInstaller.java
  src/main/java/org/commcare/resources/model/installers/XFormInstaller.java
  src/main/java/org/commcare/xml/ResourceParser.java
  src/main/java/org/javarosa/core/services/storage/IStorageUtilityIndexed.java
  src/main/java/org/javarosa/core/services/storage/util/DummyIndexedStorageUtility.java
  src/test/java/org/javarosa/core/storage/IndexedStorageUtilityTests.java
Labels: cross requested, product/internal-or-flagged

#913 Commcare 2.49
  src/main/java/org/javarosa/form/api/FormController.java
  src/main/java/org/javarosa/form/api/FormEntryController.java
Labels: cross requested, product/invisible

#915 removes install stats logging
  src/main/java/org/commcare/resources/model/InstallStatsLogger.java
  src/main/java/org/commcare/resources/model/ResourceTable.java
Labels: cross requested, product/invisible

#911 Merge last known good 'master' state into formplayer
  build.gradle
  src/main/java/org/commcare/core/network/CaptivePortalRedirectException.java
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
  src/main/java/org/commcare/core/network/ModernHttpRequester.java
  src/main/java/org/commcare/util/LogTypes.java
  src/main/java/org/javarosa/core/model/condition/EvaluationContext.java
  src/main/java/org/javarosa/xpath/expr/FunctionUtils.java
  src/main/java/org/javarosa/xpath/expr/XPathDistinctValuesFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathExpression.java
  src/main/java/org/javarosa/xpath/expr/XPathIndexOfFunc.java
  src/main/java/org/javarosa/xpath/parser/ast/ASTNodeFunctionCall.java
  src/test/java/org/javarosa/xpath/expr/test/XPathFuncExprTest.java
Labels: product/invisible

#917 Offline restore installer error handling
  src/main/java/org/commcare/resources/model/ResourceTable.java
  src/main/java/org/commcare/resources/model/installers/OfflineUserRestoreInstaller.java
  src/main/java/org/commcare/suite/model/OfflineUserRestore.java
Labels: cross requested, product/invisible
