Repository dimagi/commcare-core, pull requests merged in 2020-01, with the labels that each got.

#874 Remove catching all exceptions while localizing text
  src/main/java/org/javarosa/form/api/FormEntryPrompt.java
Labels: bug, product/invisible, ready for review

#875 Add Locale Arg Parameters for <text> implementation
  src/main/java/org/commcare/suite/model/Text.java
  src/main/java/org/commcare/xml/TextParser.java
  src/test/java/org/commcare/backend/model/AppConfiguredTextTests.java
  src/test/java/org/commcare/backend/model/TextTests.java
  src/test/resources/app_for_text_tests/default/app_strings.txt
  src/test/resources/app_for_text_tests/en/app_strings.txt
  src/test/resources/app_for_text_tests/hin/app_strings.txt
  src/test/resources/app_for_text_tests/modules-0/forms-0.xml
  src/test/resources/app_for_text_tests/modules-1/forms-0.xml
  src/test/resources/app_for_text_tests/profile.ccpr
  src/test/resources/app_for_text_tests/suite.xml
  src/test/resources/app_for_text_tests/user_restore.xml
Labels: product/invisible, ready for review

#876 Clearer regex test
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: product/invisible
