Repository dimagi/commcare-core, pull requests merged in 2020-12, with the labels that each got.

#956 Formplayer Backmerge
  build.gradle
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/util/CollectionUtils.java
  src/main/java/org/commcare/util/EntitySortUtil.java
  src/main/java/org/javarosa/core/model/data/TimeData.java
  src/main/java/org/javarosa/core/model/instance/DataInstance.java
  src/main/java/org/javarosa/core/model/utils/DateUtils.java
  src/main/java/org/javarosa/core/model/utils/TimezoneProvider.java
  src/main/java/org/javarosa/core/services/PrototypeManager.java
  src/main/java/org/javarosa/core/util/ShortestCycleAlgorithm.java
  src/main/java/org/javarosa/core/util/externalizable/ExtUtil.java
  src/main/java/org/javarosa/core/util/externalizable/SerializationLimitationException.java
  src/main/java/org/javarosa/xform/util/XFormAnswerDataSerializer.java
  src/main/java/org/javarosa/xpath/XPathLazyNodeset.java
  src/test/java/org/commcare/cases/test/CaseXPathQueryTest.java
  src/test/java/org/commcare/fixtures/test/FixtureQueryTest.java
  src/test/java/org/commcare/util/CollectionUtilsTest.java
  src/test/java/org/javarosa/core/model/data/test/TimeDataTests.java
  src/test/java/org/javarosa/core/model/test/CyclicReferenceTests.java
  src/test/java/org/javarosa/core/model/utils/test/DateUtilsTests.java
  src/test/resources/xform_tests/real_form2_with_cycle_errors.xml
Labels: product/invisible, ready for review

#949 Added auto_launch option for actions
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/main/java/org/commcare/suite/model/Action.java
  src/main/java/org/commcare/xml/ActionParser.java
  src/test/java/org/commcare/backend/session/test/SessionStackTests.java
  src/test/resources/complex_stack/suite.xml
Labels: product/invisible

#958 Added translation for Case Claim title on the 'search all cases' page
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: product/all-users

#960 Auto launching of actions, round 2
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: product/internal-or-flagged, product/invisible

#961 Revert 960 jls/autolaunch action round 2
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: product/invisible

#963 Removed try/except from Case Claim translation
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: product/all-users

#962 Added translation for Case Claim
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: product/all-users

#954 Adds Session endpoints model
  src/main/java/org/commcare/suite/model/Endpoint.java
  src/main/java/org/commcare/suite/model/StackOperation.java
  src/main/java/org/commcare/suite/model/Suite.java
  src/main/java/org/commcare/util/CommCarePlatform.java
  src/main/java/org/commcare/xml/ActionParser.java
  src/main/java/org/commcare/xml/EndpointParser.java
  src/main/java/org/commcare/xml/EntryParser.java
  src/main/java/org/commcare/xml/StackOpParser.java
  src/main/java/org/commcare/xml/SuiteParser.java
Labels: cross requested, product/invisible

#964 No badges
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/main/java/org/commcare/suite/model/MenuLoader.java
Labels: product/invisible

#959 Allow Default Expressions for Query Screen Prompts
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/xml/QueryPromptParser.java
  src/test/java/org/commcare/backend/suite/model/test/CaseClaimModelTests.java
  src/test/resources/case_claim_example/form_placeholder.xml
  src/test/resources/case_claim_example/profile.ccpr
  src/test/resources/case_claim_example/suite.xml
  src/test/resources/case_claim_example/user_restore.xml
Labels: product/invisible, ready for review

#967 Add hooks for Case claim Itemset support
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: product/invisible
