Repository dimagi/commcare-core, pull requests merged in 2020-10, with the labels that each got.

#933 Fix npe in getting case property length
  src/main/java/org/commcare/xml/CaseXmlParser.java
Labels: critical-bug-fix, product/all-users

#934 Backmerge Commcare 2.50.1
  src/main/java/org/commcare/xml/CaseXmlParser.java
Labels: product/invisible

#935 Kev/add timezone off of formplayer
  src/main/java/org/javarosa/core/model/utils/DateUtils.java
  src/main/java/org/javarosa/core/model/utils/TimezoneProvider.java
  src/test/java/org/javarosa/core/model/utils/test/DateUtilsTests.java
Labels: product/all-users

#936 store expanded entity references
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: product/invisible

#937 add option for minimal entity screen
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: product/invisible

#938 timezone offset fix
  src/main/java/org/javarosa/core/model/utils/DateUtils.java
Labels: product/all-users

#940 Corrects Cycle Detection Algo
  src/main/java/org/commcare/util/CollectionUtils.java
  src/main/java/org/javarosa/core/util/ShortestCycleAlgorithm.java
  src/test/java/org/commcare/util/CollectionUtilsTest.java
  src/test/java/org/javarosa/core/model/test/CyclicReferenceTests.java
  src/test/resources/xform_tests/real_form2_with_cycle_errors.xml
Labels: product/all-users

#942 Suppress TimeZone info on TimeData questions
  src/main/java/org/javarosa/core/model/data/TimeData.java
  src/main/java/org/javarosa/core/model/utils/DateUtils.java
  src/main/java/org/javarosa/xform/util/XFormAnswerDataSerializer.java
  src/test/java/org/javarosa/core/model/data/test/TimeDataTests.java
Labels: Release Note, bug, product/invisible, ready for review
