Repository dimagi/commcare-core, pull requests merged in 2020-05, with the labels that each got.

#893 Interrupt triggers for indexing ops
  src/main/java/org/javarosa/core/model/condition/EvaluationContext.java
  src/main/java/org/javarosa/xpath/expr/XPathExpression.java
Labels: enhancement, product/invisible, ready for review

#897 Hotfix: Allow network config
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
  src/main/java/org/commcare/core/network/HttpBuilderConfig.java
Labels: product/invisible

#900 Improves error handling for invalid select option error
  src/main/java/org/commcare/cases/util/StringUtils.java
  src/main/java/org/javarosa/core/model/data/helper/Selection.java
Labels: minor (quick review), product/invisible, ready for review

#902 Throws FNF in case resource reference don't exist
  src/main/java/org/javarosa/core/reference/ResourceReference.java
Labels: product/invisible, ready for review

#896 allow customizing network service requests
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
  src/main/java/org/commcare/core/network/HttpBuilderConfig.java
Labels: product/invisible

#873 Merge recent formplayer changes back into core
  src/main/java/org/commcare/modern/reference/ArchiveFileReference.java
Labels: product/invisible

#904 Directional IO Exceptions
  src/main/java/org/commcare/suite/model/OfflineUserRestore.java
  src/main/java/org/javarosa/core/io/StreamsUtil.java
Labels: product/invisible, ready for review

#894 Modify fuzzy search to match strings with a perfect prefix
  src/main/java/org/commcare/cases/util/StringUtils.java
  src/test/java/org/commcare/util/reference/test/FuzzySearchTest.java
Labels: enhancement, product/all-users

#895 Adds global -> geo-overlay block in Suite's Detail
  src/main/java/org/commcare/suite/model/Detail.java
  src/main/java/org/commcare/suite/model/GeoOverlay.java
  src/main/java/org/commcare/suite/model/Global.java
  src/main/java/org/commcare/xml/DetailParser.java
  src/main/java/org/commcare/xml/GeoOverlayParser.java
  src/main/java/org/commcare/xml/GlobalParser.java
  src/test/java/org/commcare/backend/suite/model/test/AppStructureTests.java
  src/test/java/org/commcare/backend/suite/model/test/EmptyAppElementsTests.java
  src/test/resources/app_structure/suite.xml
  src/test/resources/empty_app_elements/suite.xml
Labels: cross requested, enhancement, product/invisible

#898 Downgrade okhttp to 3.12.12 to support API < 21
  build.gradle
Labels: product/invisible

#907 Adds minmal platform version
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
  src/main/java/org/commcare/util/CommCarePlatform.java
  src/main/java/org/commcare/xml/ProfileParser.java
  src/main/java/org/javarosa/xml/util/UnfullfilledRequirementsException.java
Labels: cross requested, product/invisible, ready for review
