Repository dimagi/commcare-core, pull requests merged in 2020-04, with the labels that each got.

#887 Fix incorrect redirect log message
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
Labels: minor (quick review), product/invisible, ready for review

#889 Captive portal check
  src/main/java/org/commcare/core/network/CaptivePortalRedirectException.java
  src/main/java/org/commcare/core/network/ModernHttpRequester.java
Labels: cross requested, product/all-users, ready for review

#891 Index-of Expression
  src/main/java/org/javarosa/xpath/expr/FunctionUtils.java
  src/main/java/org/javarosa/xpath/expr/XPathDistinctValuesFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathIndexOfFunc.java
  src/main/java/org/javarosa/xpath/parser/ast/ASTNodeFunctionCall.java
  src/test/java/org/javarosa/xpath/expr/test/XPathFuncExprTest.java
Labels: minor (quick review), product/all-users, ready for review

#890 Add log type for in-app update
  src/main/java/org/commcare/util/LogTypes.java
Labels: cross requested, minor (quick review), product/internal-or-flagged

#892 Fix integer -> double typing
  src/main/java/org/javarosa/xpath/expr/XPathIndexOfFunc.java
  src/test/java/org/javarosa/xpath/expr/test/XPathFuncExprTest.java
Labels: minor (quick review), product/invisible
