Repository dimagi/commcare-core, pull requests merged in 2021-06, with the labels that each got.

#996 Add hidden attr to case search screen
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/xml/QueryPromptParser.java
  src/test/resources/case_claim_example/suite.xml
Labels: cross requested, enhancement, product/internal-or-flagged, product/invisible

#1001 fix joint index test
  src/test/java/org/commcare/cases/test/CaseXPathQueryTest.java
Labels: product/invisible

#999 Rotate large labels on x-axis in graph
  src/main/java/org/commcare/core/graph/c3/AxisConfiguration.java
  src/main/java/org/commcare/core/graph/util/AbsStringExtension.java
  src/main/java/org/commcare/core/graph/util/StringWidthUtil.java
Labels: enhancement, product/all-users

#1000 Endpoint Error Handling
  src/main/java/org/commcare/suite/model/Endpoint.java
Labels: product/custom

#998 Support for multi-select fields in case search
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/javarosa/core/model/utils/ItemSetUtils.java
Labels: cross requested, product/custom

#1005 Fixes case purge error handling
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
Labels: product/invisible

#1004 Formplayer to Mobile Merge
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/cases/instance/CaseChildElement.java
  src/main/java/org/commcare/cases/instance/CaseInstanceTreeElement.java
  src/main/java/org/commcare/cases/model/Case.java
  src/main/java/org/commcare/cases/query/NegativeIndexedValueLookup.java
  src/main/java/org/commcare/cases/util/CasePurgeFilter.java
  src/main/java/org/commcare/cases/util/InvalidCaseGraphException.java
  src/main/java/org/commcare/cases/util/StorageBackedTreeRoot.java
  src/main/java/org/commcare/modern/database/DatabaseHelper.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/Action.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/util/JsonUtils.java
  src/main/java/org/commcare/xml/ActionParser.java
  src/main/java/org/commcare/xml/CaseXmlParser.java
  src/main/java/org/commcare/xml/QueryPromptParser.java
  src/main/java/org/commcare/xml/bulk/BulkProcessingCaseXmlParser.java
  src/main/java/org/javarosa/core/model/utils/CacheHost.java
  src/main/java/org/javarosa/core/model/utils/ItemSetUtils.java
  src/main/java/org/javarosa/core/services/storage/IStorageUtilityIndexed.java
  src/main/java/org/javarosa/core/services/storage/util/DummyIndexedStorageUtility.java
  src/main/java/org/javarosa/core/util/DAG.java
  src/main/java/org/javarosa/form/api/FormEntryController.java
  src/main/resources/casedb_instance_structure.xml
  src/test/java/org/commcare/backend/session/test/SessionStackTests.java
  src/test/java/org/commcare/cases/test/CaseXPathQueryTest.java
  src/test/java/org/commcare/cases/util/test/CaseParseReindexTests.java
  src/test/java/org/commcare/cases/util/test/CasePurgeIntegrationTest.java
  src/test/java/org/commcare/cases/util/test/CasePurgeRegressions.java
  src/test/java/org/commcare/test/utilities/CasePurgeTest.java
  src/test/java/org/commcare/util/JsonUtilsTest.java
  src/test/resources/case_claim_example/suite.xml
  src/test/resources/case_purge/cyclic_case_relationship_test.xml
  src/test/resources/case_query_testing.xml
  src/test/resources/index_disruption/case_add_index.xml
  src/test/resources/index_disruption/case_update_clean.xml
Labels: cross requested, product/invisible

#1009 Renamed function
  src/main/java/org/commcare/suite/model/Endpoint.java
Labels: product/invisible
