Repository dimagi/commcare-core, pull requests merged in 2021-03, with the labels that each got.

#975 Auto Advance with auto launch in a single request
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/screen/CompoundScreenHost.java
  src/cli/java/org/commcare/util/screen/EntityDetailSubscreen.java
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/cli/java/org/commcare/util/screen/Screen.java
  src/cli/java/org/commcare/util/screen/Subscreen.java
  src/cli/java/org/commcare/util/screen/SyncScreen.java
Labels: product/invisible

#982 skip defaults for not supported prompts
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/test/java/org/commcare/backend/session/test/SessionStackTests.java
Labels: cross requested, product/invisible

#983 Backmerge Commcare 2.51.2
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/DisplayData.java
  src/main/java/org/commcare/suite/model/DisplayUnit.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/xml/CommCareElementParser.java
  src/test/java/org/commcare/backend/session/test/SessionStackTests.java
Labels: product/invisible

#985 Break out of purge in case of cycles
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/main/java/org/commcare/cases/util/CasePurgeFilter.java
  src/main/java/org/commcare/cases/util/InvalidCaseGraphException.java
  src/main/java/org/javarosa/core/util/DAG.java
  src/test/java/org/commcare/cases/util/test/CasePurgeIntegrationTest.java
  src/test/java/org/commcare/cases/util/test/CasePurgeRegressions.java
  src/test/java/org/commcare/test/utilities/CasePurgeTest.java
  src/test/resources/case_purge/cyclic_case_relationship_test.xml
Labels: cross requested, product/invisible, ready for review
