Repository dimagi/commcare-core, pull requests merged in 2021-02, with the labels that each got.

#971 Skip to Default Search and Search Again
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/Action.java
  src/main/java/org/commcare/suite/model/RemoteQueryDatum.java
  src/main/java/org/commcare/xml/ActionParser.java
  src/main/java/org/commcare/xml/SessionDatumParser.java
Labels: product/custom, product/internal-or-flagged

#976 reuse xformparser method for loading form XML into form def
  src/main/java/org/javarosa/xform/parse/XFormParser.java
  src/translate/java/org/javarosa/xform/schema/FormInstanceLoader.java
Labels: product/invisible

#974 Adds hint to case claim prompt
  src/main/java/org/commcare/suite/model/DisplayData.java
  src/main/java/org/commcare/suite/model/DisplayUnit.java
  src/main/java/org/commcare/xml/CommCareElementParser.java
Labels: product/all-users, ready for review

#978 Add receive attribute to QueryPrompt
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/xml/QueryPromptParser.java
Labels: product/all-users
