Repository dimagi/commcare-core, pull requests merged in 2021-04, with the labels that each got.

#986 Detect DAG cycles in case graphs explicitly
  src/main/java/org/commcare/cases/util/CasePurgeFilter.java
  src/main/java/org/javarosa/core/util/DAG.java
Labels: bug, product/invisible

#984 Formplayer Merge
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/engine/CommCareConfigEngine.java
  src/cli/java/org/commcare/util/screen/CompoundScreenHost.java
  src/cli/java/org/commcare/util/screen/EntityDetailSubscreen.java
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/cli/java/org/commcare/util/screen/Screen.java
  src/cli/java/org/commcare/util/screen/Subscreen.java
  src/cli/java/org/commcare/util/screen/SyncScreen.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/Action.java
  src/main/java/org/commcare/suite/model/MenuLoader.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/suite/model/RemoteQueryDatum.java
  src/main/java/org/commcare/xml/ActionParser.java
  src/main/java/org/commcare/xml/QueryPromptParser.java
  src/main/java/org/commcare/xml/SessionDatumParser.java
  src/test/java/org/commcare/backend/session/test/SessionStackTests.java
  src/test/resources/complex_stack/suite.xml
Labels: cross requested, product/invisible

#979 Refactoring to support Case search cache
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
Labels: cross requested, product/invisible

#987 add method to check for presence of case id
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: product/invisible

#992 Revert "Revert "add method to check for presence of case id""
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: product/invisible
