Repository dimagi/commcare-core, pull requests merged in 2021-09, with the labels that each got.

#1038 CLI remote query entry (II)
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/mocks/MockQueryClient.java
  src/cli/java/org/commcare/util/screen/CompoundScreenHost.java
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/cli/java/org/commcare/util/screen/Screen.java
  src/cli/java/org/commcare/util/screen/SyncScreen.java
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/test/java/org/commcare/backend/suite/model/test/QueryModelTests.java
  src/test/resources/case_claim_example/query_response.xml
  src/test/resources/case_claim_example/suite.xml
Labels: product/invisible

#1017 Allow searching for Blank values
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/xml/QueryPromptParser.java
  src/test/resources/case_claim_example/suite.xml
Labels: cross requested, product/invisible

#1037 Add tests for prettify xml
  src/test/java/org/commcare/util/XmlUtilTest.java
  src/test/resources/minified_xml.xml
  src/test/resources/pretty_printed_xml.xml
Labels: product/invisible

#1024 Added CLI support for case claim in session endpoints
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
Labels: product/invisible

#1036 Revert "Revert "(formplayer) Fixed case details and case search workf…
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/screen/CompoundScreenHost.java
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/cli/java/org/commcare/util/screen/SyncScreen.java
  src/test/java/org/cli/CliTests.java
  src/test/resources/app_with_child_modules/modules-0/forms-0.xml
  src/test/resources/app_with_child_modules/modules-1/forms-0.xml
  src/test/resources/app_with_child_modules/profile.ccpr
  src/test/resources/app_with_child_modules/suite.xml
  src/test/resources/app_with_child_modules/user_restore.xml
Labels: product/invisible

#1041 Remove unreachable return statement
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
Labels: minor (quick review), product/invisible

#1043 Updated refreshItemSetChoices to quit if no prompts
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
Labels: product/invisible, product/internal-or-flagged

#1044 Better wording for error message
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: product/custom

#1047 remove artificial constraint on 'casedb' instance naming
  src/main/java/org/commcare/cases/instance/CaseDataInstance.java
Labels: product/invisible
