Repository dimagi/commcare-core, pull requests merged in 2021-05, with the labels that each got.

#973 Case search dependent itemset fix
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: product/invisible

#993 API for auto advancing a menu screen with single option
  src/cli/java/org/commcare/util/screen/MenuScreen.java
Labels: cross requested, product/custom

#989 Adds ability to specify Action auto launch as an xpath condition
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/main/java/org/commcare/suite/model/Action.java
  src/main/java/org/commcare/xml/ActionParser.java
  src/test/java/org/commcare/backend/session/test/SessionStackTests.java
Labels: cross requested, product/custom

#994 Handle captive portals in app install
  src/main/java/org/commcare/core/network/CaptivePortalRedirectException.java
  src/main/java/org/commcare/core/network/ModernHttpRequester.java
  src/main/java/org/commcare/modern/reference/JavaHttpReference.java
  src/main/java/org/commcare/resources/model/installers/LocaleFileInstaller.java
  src/main/java/org/commcare/resources/model/installers/ProfileInstaller.java
  src/main/java/org/commcare/resources/model/installers/SuiteInstaller.java
  src/main/java/org/commcare/resources/model/installers/XFormInstaller.java
  src/main/java/org/commcare/util/NetworkStatus.java
Labels: enhancement, product/all-users

#995 Adds Json utility class
  src/main/java/org/commcare/util/JsonUtils.java
  src/test/java/org/commcare/util/JsonUtilsTest.java
Labels: cross requested, product/invisible

#990 Get case name using 'case-name-descriptor' itext entry
  src/main/java/org/commcare/util/FormMetaIndicatorUtil.java
Labels: bug, cross requested, product/internal-or-flagged, product/invisible

#997 debug log
  src/main/java/org/javarosa/form/api/FormEntryController.java
Labels: product/invisible
