Repository dimagi/commcare-core, pull requests merged in 2021-07, with the labels that each got.

#1011 Rotate 75 degrees for all values
  src/main/java/org/commcare/core/graph/c3/AxisConfiguration.java
  src/main/java/org/commcare/core/graph/c3/Configuration.java
  src/main/java/org/commcare/core/graph/c3/DataConfiguration.java
  src/main/java/org/commcare/core/graph/model/GraphData.java
Labels: product/all-users

#1014 Fix issues with graph label overlapping
  src/main/java/org/commcare/core/graph/c3/AxisConfiguration.java
  src/main/java/org/commcare/core/graph/c3/DataConfiguration.java
Labels: product/all-users

#1002 Supports Case Search for Multi-Valued Keys
  build.gradle
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/RemoteQueryDatum.java
  src/main/java/org/commcare/xml/SessionDatumParser.java
  src/main/java/org/javarosa/core/util/externalizable/ExtWrapMultiMap.java
  src/main/java/org/javarosa/core/util/externalizable/ExtWrapTagged.java
  src/test/java/org/javarosa/core/util/test/ExternalizableTest.java
Labels: cross requested, product/invisible

#1016 Avoid having Duplicate params in case search
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
Labels: product/invisible

#1015 Graph character limit
  src/main/java/org/commcare/core/graph/c3/AxisConfiguration.java
  src/main/java/org/commcare/core/graph/c3/DataConfiguration.java
  src/main/java/org/commcare/core/graph/model/GraphData.java
  src/main/java/org/commcare/core/graph/util/AbsStringExtension.java
  src/main/java/org/commcare/core/graph/util/GraphUtil.java
  src/main/java/org/commcare/core/graph/util/StringWidthUtil.java
Labels: product/all-users

#1013 Mobile (2.52) to Formplayer Merge
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/core/graph/c3/AxisConfiguration.java
  src/main/java/org/commcare/core/graph/util/AbsStringExtension.java
  src/main/java/org/commcare/core/graph/util/StringWidthUtil.java
  src/main/java/org/commcare/core/network/CaptivePortalRedirectException.java
  src/main/java/org/commcare/core/network/CommCareNetworkService.java
  src/main/java/org/commcare/core/network/ModernHttpRequester.java
  src/main/java/org/commcare/modern/reference/JavaHttpReference.java
  src/main/java/org/commcare/resources/model/installers/LocaleFileInstaller.java
  src/main/java/org/commcare/resources/model/installers/ProfileInstaller.java
  src/main/java/org/commcare/resources/model/installers/SuiteInstaller.java
  src/main/java/org/commcare/resources/model/installers/XFormInstaller.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/Endpoint.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/util/FormMetaIndicatorUtil.java
  src/main/java/org/commcare/util/NetworkStatus.java
  src/main/java/org/commcare/xml/CaseXmlParser.java
  src/main/java/org/javarosa/xform/parse/XFormParser.java
  src/test/java/org/commcare/backend/session/test/SessionStackTests.java
  src/test/java/org/commcare/cases/util/test/CaseParseReindexTests.java
  src/test/resources/index_disruption/case_add_index.xml
  src/test/resources/index_disruption/case_update_clean.xml
  src/translate/java/org/javarosa/xform/schema/FormInstanceLoader.java
Labels: product/invisible

#1003 Adds Encryption utils for AES
  src/main/java/org/commcare/util/EncryptionUtils.java
  src/main/java/org/javarosa/xpath/XPathException.java
  src/main/java/org/javarosa/xpath/expr/XPathEncryptStringFunc.java
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: cross requested, product/invisible

#1019 Fixed case details and case search workflows in CLI
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/screen/CompoundScreenHost.java
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/cli/java/org/commcare/util/screen/SyncScreen.java
  src/test/java/org/cli/CliTests.java
  src/test/resources/app_with_child_modules/modules-0/forms-0.xml
  src/test/resources/app_with_child_modules/modules-1/forms-0.xml
  src/test/resources/app_with_child_modules/profile.ccpr
  src/test/resources/app_with_child_modules/suite.xml
  src/test/resources/app_with_child_modules/user_restore.xml
Labels: product/invisible
