Repository dimagi/commcare-core, pull requests merged in 2021-12, with the labels that each got.

#1060 Switch case search to make a post request (redo)
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/javarosa/core/model/instance/ExternalDataInstanceSource.java
  src/test/java/org/commcare/backend/session/test/SessionStackTests.java
Labels: product/invisible

#1006 Removes duplicate code from Formplayer and Android for CaseInstanceTreeElement
  src/main/java/org/commcare/cases/instance/CaseInstanceTreeElement.java
  src/test/java/org/commcare/cases/test/CaseXPathQueryTest.java
Labels: product/invisible

#1008 Removes duplicate code from Formplayer and Android for CaseInstanceTreeElement
  src/main/java/org/commcare/cases/instance/CaseInstanceTreeElement.java
  src/test/java/org/commcare/cases/test/CaseXPathQueryTest.java
Labels: cross requested, product/invisible

#1061 support multiple extras with the same key in stack frames
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/session/SessionFrame.java
  src/main/java/org/commcare/suite/model/StackFrameStep.java
  src/test/java/org/commcare/backend/session/test/SessionNavigatorTests.java
  src/test/java/org/commcare/backend/suite/model/test/StackFrameStepTests.java
  src/test/resources/queries_in_entry_and_stack/app_strings.txt
  src/test/resources/queries_in_entry_and_stack/placeholder_form.xml
  src/test/resources/queries_in_entry_and_stack/profile.ccpr
  src/test/resources/queries_in_entry_and_stack/suite.xml
  src/test/resources/queries_in_entry_and_stack/user_restore.xml
Labels: product/all-users
