Repository dimagi/commcare-core, pull requests merged in 2022-12, with the labels that each got.

#1189 Trigger dependabot version updates for formplayer
  .github/dependabot.yml
Labels: product/invisible, dependencies

#1176 Master to Formplayer Backmerge
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/build.yml
  build.gradle
  src/ccapi/resources/blank_file_needed_for_jmh_gradle_plugin
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/cli/java/org/commcare/util/screen/SyncScreen.java
  src/main/java/org/commcare/core/network/CommCareNetworkService.java
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
  src/main/java/org/commcare/core/network/ModernHttpRequester.java
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/session/SessionFrame.java
  src/main/java/org/commcare/suite/model/AndroidPackageDependency.java
  src/main/java/org/commcare/suite/model/Profile.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/suite/model/RemoteQueryDatum.java
  src/main/java/org/commcare/suite/model/StackFrameStep.java
  src/main/java/org/commcare/util/EncryptionUtils.java
  src/main/java/org/commcare/util/NetworkStatus.java
  src/main/java/org/commcare/xml/ProfileParser.java
  src/main/java/org/commcare/xml/SessionDatumParser.java
  src/main/java/org/javarosa/core/model/FormDef.java
  src/main/java/org/javarosa/core/model/actions/FormSendCalloutHandler.java
  src/main/java/org/javarosa/core/model/actions/SendAction.java
  src/main/java/org/javarosa/core/model/data/helper/Selection.java
  src/main/java/org/javarosa/core/reference/ResourceReference.java
  src/main/java/org/javarosa/xpath/expr/FunctionUtils.java
  src/main/java/org/javarosa/xpath/expr/XPathDecryptStringFunc.java
  src/main/java/org/javarosa/xpath/parser/ast/ASTNodeFunctionCall.java
  src/test/java/org/commcare/backend/session/test/SessionStackTests.java
  src/test/java/org/commcare/backend/suite/model/test/ProfileTests.java
  src/test/java/org/commcare/xml/SessionDatumParserTest.java
  src/test/java/org/javarosa/test_utils/MockFormSendCalloutHandler.java
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
  src/test/resources/app_structure/profile.ccpr
  src/test/resources/basic_profile.ccpr
  src/test/resources/case_relationship_tests.json
  src/test/resources/pretty_printed_xml.xml
  src/translate/java/org/javarosa/engine/xml/XmlUtil.java
Labels: product/invisible

#1204 Fix no cases in auto select Mode
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
Labels: cross requested, product/invisible

#1206 Add fillTriggeredElement tracing
  src/main/java/org/javarosa/core/model/FormDef.java
Labels: minor (quick review), product/invisible
