Repository dimagi/commcare-core, pull requests merged in 2022-05, with the labels that each got.

#1105 Added MultiSelectEntityScreen.getVirtualInstance
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
Labels: product/invisible

#1034 Updates to AGP 7
  .github/workflows/build.yml
  build.gradle
  src/ccapi/resources/blank_file_needed_for_jmh_gradle_plugin
  src/main/java/org/javarosa/core/reference/ResourceReference.java
  src/test/resources/pretty_printed_xml.xml
  src/translate/java/org/javarosa/engine/xml/XmlUtil.java
Labels: cross requested, product/invisible

#912 Reword error message
  src/main/java/org/javarosa/core/model/data/helper/Selection.java
Labels: product/all-users

#1031 Add tests for child and extension relationship
  src/test/resources/case_relationship_tests.json
Labels: product/invisible

#1070 Removed unused private var from QueryScreen
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: product/invisible

#1107 CLI improvements that make it easier to test remote requests
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/cli/CliPlayCommand.java
  src/cli/java/org/commcare/util/screen/SessionUtils.java
Labels: product/invisible

#1113 Only create new storage if needed (formplayer)
  src/main/java/org/javarosa/core/services/storage/IStorageUtilityIndexed.java
  src/main/java/org/javarosa/core/services/storage/StorageManager.java
  src/main/java/org/javarosa/core/services/storage/util/DummyIndexedStorageUtility.java
Labels: product/invisible

#1082 Session navigation for Multi Select Case List
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/screen/CompoundScreenHost.java
  src/cli/java/org/commcare/util/screen/EntityDetailSubscreen.java
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/cli/java/org/commcare/util/screen/Screen.java
  src/cli/java/org/commcare/util/screen/Subscreen.java
  src/cli/java/org/commcare/util/screen/SyncScreen.java
  src/jmh/java/org/commcare/LoadAndInitLargeForm.java
  src/main/java/org/commcare/core/interfaces/RemoteInstanceFetcher.java
  src/main/java/org/commcare/core/interfaces/VirtualDataInstanceStorage.java
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/commcare/data/xml/SimpleNode.java
  src/main/java/org/commcare/data/xml/VirtualInstances.java
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/session/SessionFrame.java
  src/main/java/org/commcare/session/SessionInstanceBuilder.java
  src/main/java/org/commcare/session/SessionNavigator.java
  src/main/java/org/commcare/suite/model/PostRequest.java
  src/main/java/org/javarosa/core/model/instance/ExternalDataInstance.java
  src/main/java/org/javarosa/core/model/instance/ExternalDataInstanceSource.java
  src/main/java/org/javarosa/core/model/instance/VirtualDataInstance.java
  src/main/java/org/javarosa/core/reference/ReferenceHandler.java
  src/main/java/org/javarosa/core/services/locale/LocalizerManager.java
  src/test/java/org/commcare/backend/session/test/BasicSessionNavigationTests.java
  src/test/java/org/commcare/backend/session/test/ChildModuleNavigationTests.java
  src/test/java/org/commcare/backend/session/test/MarkRewindSessionTests.java
  src/test/java/org/commcare/backend/session/test/SessionNavigatorTests.java
  src/test/java/org/commcare/backend/session/test/SessionStackTests.java
  src/test/java/org/commcare/backend/suite/model/test/CaseClaimModelTests.java
  src/test/java/org/commcare/backend/suite/model/test/QueryModelTests.java
  src/test/java/org/commcare/backend/suite/model/test/StackFrameStepTests.java
  src/test/java/org/commcare/backend/test/TemplateStructureTest.java
  src/test/java/org/commcare/data/xml/VirtualInstancesTest.java
  src/test/java/org/commcare/xml/RemoteRequestEntryParserTest.java
  src/test/java/org/commcare/xml/TestInstances.java
  src/test/resources/session-tests-template/suite.xml
Labels: product/invisible

#1114 Screen cleanup [No op]
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/MenuScreen.java
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
  src/cli/java/org/commcare/util/screen/Screen.java
  src/cli/java/org/commcare/util/screen/ScreenUtils.java
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/util/FormDataUtil.java
Labels: product/invisible

#1115 Added dates to supported case search prompts
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
Labels: product/invisible
