Repository dimagi/commcare-core, pull requests merged in 2022-11, with the labels that each got.

#1159 [No Op] Removes Migration Instance Related code
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
Labels: product/invisible

#1151 Adds support for adding multimap params to cc network service
  src/main/java/org/commcare/core/network/CommCareNetworkService.java
  src/main/java/org/commcare/core/network/CommCareNetworkServiceGenerator.java
  src/main/java/org/commcare/core/network/ModernHttpRequester.java
  src/main/java/org/commcare/util/NetworkStatus.java
  src/main/java/org/javarosa/core/model/FormDef.java
  src/main/java/org/javarosa/core/model/actions/FormSendCalloutHandler.java
  src/main/java/org/javarosa/core/model/actions/SendAction.java
  src/test/java/org/javarosa/test_utils/MockFormSendCalloutHandler.java
Labels: product/invisible

#1162 Some last fixes for formplayer -> Master Merge
  src/main/java/org/commcare/core/network/ModernHttpRequester.java
  src/main/java/org/commcare/session/CommCareSession.java
Labels: cross requested, product/invisible

#1152 Adds support for auto selecting multiple cases at once
  src/cli/java/org/commcare/util/exception/InvalidEntitiesSelectionException.java
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
  src/main/java/org/commcare/suite/model/MultiSelectEntityDatum.java
  src/main/java/org/commcare/xml/SessionDatumParser.java
Labels: cross requested, product/custom

#1163 wireframing to remove all extras for a key from session frame step
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/session/SessionFrame.java
  src/main/java/org/commcare/suite/model/StackFrameStep.java
Labels: product/invisible

#1167 Revert "Revert "Adds support for auto selecting multiple cases at once ""
  src/cli/java/org/commcare/util/exception/InvalidEntitiesSelectionException.java
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
  src/main/java/org/commcare/suite/model/MultiSelectEntityDatum.java
  src/main/java/org/commcare/xml/SessionDatumParser.java
Labels: product/custom

#1168 Retains original if condition
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: product/invisible

#1164 Case search subtitle/description text
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/suite/model/RemoteQueryDatum.java
  src/main/java/org/commcare/xml/SessionDatumParser.java
  src/test/java/org/commcare/backend/suite/model/test/CaseClaimModelTests.java
  src/test/resources/case_claim_example/app_strings.txt
  src/test/resources/case_claim_example/suite.xml
Labels: product/invisible

#1170 Docs on duplicating PR across `master` and `formplayer`
  .github/contributing.md
Labels: product/invisible

#1169 Fixed Ethiopian and Nepali date conversion functions
  src/main/java/org/javarosa/core/model/utils/DateUtils.java
  src/main/java/org/javarosa/xform/util/CalendarUtils.java
Labels: bug, product/all-users

#1177 Changed fromMillis to work with calls coming from commcare-android
  src/main/java/org/javarosa/xform/util/CalendarUtils.java
Labels: minor (quick review), product/all-users

#1178 Changed fromMillis to work with calls coming from commcare-android
  src/main/java/org/javarosa/xform/util/CalendarUtils.java
Labels: minor (quick review), product/invisible

#1179 Formplayer dependabot/gradle/junit junit 4.13.2
  build.gradle
Labels: product/invisible

#1180 Bump joda-time from 2.9.4 to 2.12.1
  build.gradle
Labels: product/invisible

#1181 Bump rxjava from 2.1.1 to 2.2.21
  build.gradle
Labels: product/invisible

#1182 Bump sqlite-jdbc from 3.28.0 to 3.40.0.0
  build.gradle
Labels: product/invisible, dependencies
