Repository dimagi/commcare-core, pull requests merged in 2022-06, with the labels that each got.

#1116 Skip evaluating Entity Detail fields if current request is not for Entity Detail Screen
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
Labels: product/invisible

#1117 Process entity references as input to Multi-Select Screen
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
Labels: product/invisible

#1108 Support 'post' requests from form entry
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/screen/SessionUtils.java
  src/cli/java/org/commcare/util/screen/SyncScreen.java
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/suite/model/Entry.java
  src/main/java/org/commcare/suite/model/FormEntry.java
  src/main/java/org/commcare/suite/model/RemoteRequestEntry.java
  src/main/java/org/commcare/xml/EntryParser.java
  src/main/java/org/javarosa/core/model/Constants.java
  src/test/java/org/cli/CliTests.java
  src/test/java/org/cli/MockSessionUtils.java
  src/test/java/org/commcare/backend/session/test/BasicSessionNavigationTests.java
  src/test/java/org/commcare/xml/EntryParserTest.java
  src/test/resources/session-tests-template/default/app_strings.txt
  src/test/resources/session-tests-template/suite.xml
Labels: product/all-users

#1112 store case search user input in the session for later access
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/core/encryption/CryptUtil.java
  src/main/java/org/commcare/core/interfaces/MemoryVirtualDataInstanceStorage.java
  src/main/java/org/commcare/core/interfaces/VirtualDataInstanceStorage.java
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/commcare/data/xml/VirtualInstances.java
  src/main/java/org/commcare/modern/session/SessionWrapper.java
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/StackFrameStep.java
  src/main/java/org/javarosa/core/model/instance/ExternalDataInstanceSource.java
  src/test/java/org/commcare/backend/suite/model/test/CaseClaimModelTests.java
  src/test/java/org/commcare/backend/suite/model/test/QueryModelTests.java
  src/test/java/org/commcare/backend/suite/model/test/StackFrameStepTests.java
  src/test/java/org/commcare/data/xml/VirtualInstancesTest.java
  src/test/resources/case_claim_example/app_strings.txt
  src/test/resources/case_claim_example/suite.xml
Labels: product/invisible

#950 ensure the session is the same
  src/cli/java/org/commcare/util/screen/EntityScreen.java
Labels: product/invisible

#1119 reverts exact instance matching due to errors with existing apps
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
Labels: bug, product/invisible

#1123 [Test fix] Configure locales for localised calendars tests
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: product/invisible

#1118 Add Multi Select Case Lists to CLI
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/screen/CompoundScreenHost.java
  src/cli/java/org/commcare/util/screen/EntityListSubscreen.java
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
Labels: product/invisible

#1122 get json property by name
  src/main/java/org/javarosa/xpath/expr/FunctionUtils.java
  src/main/java/org/javarosa/xpath/expr/XPathJsonPropertyFunc.java
  src/test/java/org/javarosa/xpath/expr/test/XPathJsonPropertyFuncTest.java
Labels: product/custom

#1128 add json property func
  src/main/java/org/javarosa/xpath/expr/FunctionUtils.java
  src/main/java/org/javarosa/xpath/expr/XPathJsonPropertyFunc.java
  src/test/java/org/javarosa/xpath/expr/test/XPathJsonPropertyFuncTest.java
Labels: product/custom

#1126 Sk/next input multi select
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/mocks/MockQueryClient.java
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/cli/java/org/commcare/util/screen/SessionUtils.java
  src/main/java/org/commcare/core/interfaces/MemoryVirtualDataInstanceStorage.java
  src/main/java/org/commcare/core/interfaces/VirtualDataInstanceStorage.java
  src/main/java/org/javarosa/core/model/instance/TreeElement.java
  src/main/java/org/javarosa/core/model/instance/utils/TreeUtilities.java
  src/test/java/org/cli/CliTests.java
  src/test/java/org/cli/MockSessionUtils.java
  src/test/java/org/commcare/backend/suite/model/test/QueryModelTests.java
  src/test/java/org/commcare/backend/suite/model/test/StackFrameStepTests.java
  src/test/resources/session-tests-template/query_response.xml
  src/test/resources/session-tests-template/suite.xml
Labels: product/invisible

#1127 stack observer
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/session/SessionFrame.java
  src/main/java/org/commcare/session/StackObserver.java
  src/test/java/org/commcare/backend/session/test/StackObserverTest.java
Labels: product/invisible

#1129 simplify observer interface
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/session/SessionFrame.java
  src/main/java/org/commcare/session/StackObserver.java
  src/test/java/org/commcare/backend/session/test/StackObserverTest.java
Labels: product/invisible

#1124 Changes virtual instance source reference
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/commcare/data/xml/VirtualInstances.java
  src/main/java/org/commcare/suite/model/StackFrameStep.java
  src/main/java/org/javarosa/core/model/instance/ExternalDataInstanceSource.java
Labels: product/invisible

#1132 Tests updating input updates the search input instance
  src/main/java/org/javarosa/core/model/condition/EvaluationContext.java
  src/test/java/org/commcare/backend/suite/model/test/CaseClaimModelTests.java
Labels: product/invisible

#1130 just in time virtual instances
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/cases/instance/CaseDataInstance.java
  src/main/java/org/commcare/data/xml/VirtualInstances.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/javarosa/core/model/FormDef.java
  src/main/java/org/javarosa/core/model/condition/EvaluationContext.java
  src/main/java/org/javarosa/core/model/instance/ExternalDataInstance.java
  src/main/java/org/javarosa/core/model/instance/utils/TreeUtilities.java
  src/test/java/org/commcare/backend/suite/model/test/CaseClaimModelTests.java
  src/test/java/org/commcare/backend/suite/model/test/QueryModelTests.java
  src/test/java/org/commcare/data/xml/VirtualInstancesTest.java
  src/test/resources/case_claim_example/suite.xml
Labels: product/invisible

#1134 copy context instead of using fresh context
  src/main/java/org/javarosa/core/model/FormDef.java
Labels: product/invisible
