Repository dimagi/commcare-core, pull requests merged in 2022-08, with the labels that each got.

#1144 Adds method to copy a inputstream to a file
  src/main/java/org/commcare/util/FileUtils.java
Labels: product/invisible

#1145 separate cache class for local caches
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/javarosa/core/model/FormDef.java
  src/main/java/org/javarosa/core/model/instance/DataInstance.java
  src/main/java/org/javarosa/core/util/LocalCacheTable.java
Labels: product/invisible

#1140 Parses Android dependencies
  src/main/java/org/commcare/suite/model/AndroidPackageDependency.java
  src/main/java/org/commcare/suite/model/Profile.java
  src/main/java/org/commcare/xml/ProfileParser.java
  src/test/java/org/commcare/backend/suite/model/test/ProfileTests.java
  src/test/resources/app_structure/profile.ccpr
  src/test/resources/basic_profile.ccpr
Labels: cross requested, product/invisible

#1146 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: product/invisible

#1147 File Utility methods
  src/main/java/org/commcare/util/FileUtils.java
  src/main/java/org/javarosa/core/util/ArrayUtilities.java
Labels: product/invisible

#1139 Dynamic required Conditions + Custom Required Messaging
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/suite/model/QueryPromptCondition.java
  src/main/java/org/commcare/xml/QueryPromptParser.java
  src/test/java/org/commcare/backend/suite/model/test/CaseClaimModelTests.java
  src/test/java/org/commcare/xml/QueryDataParserTest.java
  src/test/resources/case_claim_example/app_strings.txt
  src/test/resources/case_claim_example/suite.xml
Labels: product/custom

#1110 Query.init Search Screen Title value change
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/suite/model/RemoteQueryDatum.java
  src/main/java/org/commcare/xml/SessionDatumParser.java
  src/test/java/org/commcare/xml/SessionDatumParserTest.java
Labels: minor (quick review), ready for review, product/custom
