Repository dimagi/commcare-core, pull requests merged in 2022-04, with the labels that each got.

#1083 return TreeElement directly for session instance
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/commcare/session/SessionInstanceBuilder.java
Labels: product/invisible

#1084 Initializes Selected cases instance For Multi Select Case Lists
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
  src/main/java/org/commcare/core/interfaces/EntitiesSelectionCache.java
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/commcare/data/xml/SimpleNode.java
  src/main/java/org/commcare/data/xml/VirtualInstances.java
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/session/SessionFrame.java
  src/main/java/org/commcare/session/SessionInstanceBuilder.java
Labels: product/custom

#1087 Github Actions on master
  .github/workflows/build.yml
Labels: product/invisible

#1089 update stickler and checkstyle config for master
  .stickler.yml
  config/checkstyle/checkstyle.xml
Labels: product/invisible

#1088 Adds 'decrypt-string' Xpath Function
  src/main/java/org/commcare/util/EncryptionUtils.java
  src/main/java/org/javarosa/xpath/expr/FunctionUtils.java
  src/main/java/org/javarosa/xpath/expr/XPathDecryptStringFunc.java
  src/main/java/org/javarosa/xpath/parser/ast/ASTNodeFunctionCall.java
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: Release Note, product/all-users

#1091 Multi Select Case Lists - EOF Navigation
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/jmh/java/org/commcare/LoadAndInitLargeForm.java
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/session/SessionNavigator.java
  src/test/java/org/commcare/backend/session/test/BasicSessionNavigationTests.java
  src/test/java/org/commcare/backend/session/test/ChildModuleNavigationTests.java
  src/test/java/org/commcare/backend/session/test/MarkRewindSessionTests.java
  src/test/java/org/commcare/backend/session/test/SessionNavigatorTests.java
  src/test/java/org/commcare/backend/session/test/SessionStackTests.java
  src/test/java/org/commcare/backend/suite/model/test/StackFrameStepTests.java
  src/test/java/org/commcare/backend/test/TemplateStructureTest.java
Labels: product/invisible

#1090 use standard library for regex
  build.gradle
  src/main/java/org/javarosa/xpath/expr/XPathRegexFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathReplaceFunc.java
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: bug, product/all-users

#1092 use standard library for regex (master PR)
  build.gradle
  src/main/java/org/javarosa/xpath/expr/XPathRegexFunc.java
  src/main/java/org/javarosa/xpath/expr/XPathReplaceFunc.java
  src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Labels: product/invisible

#1085 added exclude from search functionality
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/xml/QueryPromptParser.java
  src/test/java/org/commcare/backend/suite/model/test/CaseClaimModelTests.java
  src/test/resources/case_claim_example/suite.xml
Labels: product/custom, product/internal-or-flagged

#1096 exclude user input from search filters
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/xml/QueryPromptParser.java
Labels: product/custom

#1099 add method to parser
  src/main/java/org/commcare/xml/QueryPromptParser.java
Labels: product/custom

#1100 add method to parser
  src/main/java/org/commcare/xml/QueryPromptParser.java
Labels: product/custom

#1097 Support for Post Relevancy based on post body params
  src/cli/java/org/commcare/util/screen/SyncScreen.java
  src/main/java/org/commcare/suite/model/PostRequest.java
  src/test/java/org/commcare/backend/session/test/BasicSessionNavigationTests.java
  src/test/java/org/commcare/xml/RemoteRequestEntryParserTest.java
  src/test/java/org/commcare/xml/TestInstances.java
  src/test/resources/session-tests-template/suite.xml
Labels: product/custom

#1102 Dont wait for case detail if user selected action (master)
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
Labels: bug, minor (quick review), product/custom

#1093 Dont wait for case detail if user selected action
  src/cli/java/org/commcare/util/cli/ApplicationHost.java
Labels: bug, minor (quick review), product/custom

#1098 Switch entities selection to a generic xml instance interface
  src/cli/java/org/commcare/util/screen/MultiSelectEntityScreen.java
  src/main/java/org/commcare/core/interfaces/VirtualDataInstanceCache.java
  src/main/java/org/commcare/data/xml/VirtualInstances.java
  src/main/java/org/javarosa/core/reference/ReferenceHandler.java
Labels: product/invisible

#1094 CLI - dont sync if case claim request returns 204
  src/cli/java/org/commcare/util/screen/SyncScreen.java
Labels: minor (quick review), product/custom

#1103 Dont sync if case claim request returns 204 (master)
  src/cli/java/org/commcare/util/screen/SyncScreen.java
Labels: bug, minor (quick review), product/custom
