Repository dimagi/commcare-core, pull requests merged in 2022-07, with the labels that each got.

#1135 fix loading of legacy search-input instances
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/commcare/suite/model/StackFrameStep.java
  src/test/java/org/commcare/backend/suite/model/test/QueryModelTests.java
Labels: product/invisible

#1138 Case search validation Conditions
  src/cli/java/org/commcare/util/screen/QueryScreen.java
  src/main/java/org/commcare/session/RemoteQuerySessionManager.java
  src/main/java/org/commcare/suite/model/QueryPrompt.java
  src/main/java/org/commcare/suite/model/QueryPromptValidation.java
  src/main/java/org/commcare/xml/QueryPromptParser.java
  src/test/java/org/commcare/backend/suite/model/test/CaseClaimModelTests.java
  src/test/resources/case_claim_example/app_strings.txt
  src/test/resources/case_claim_example/suite.xml
Labels: product/custom

#1141 Added refresh of state before answering prompts
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: product/all-users

#1143 Revert "Added refresh of state before answering prompts"
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: product/invisible

#1142 Fixes Dependent Itemsets Selection in Case search
  src/cli/java/org/commcare/util/screen/QueryScreen.java
Labels: product/invisible
