Repository dimagi/commcare-core, pull requests merged in 2023-04, with the labels that each got.

#1259 Duplicate PR Github Action
  .github/contributing.md
  .github/workflows/duplicate_pr.yml
  scripts/duplicate_pr.py
Labels: ready for review

#1263 Duplicate PR Script Bug Fix
  scripts/duplicate_pr.py
Labels: bug, minor (quick review), ready for review

#1269 Highlight duplication steps within PR
  .github/PULL_REQUEST_TEMPLATE.md
Labels: minor (quick review)

#1272 Simplify instructions for Android testing
  .github/contributing.md
Labels: product/invisible
