Repository dimagi/commcare-core, pull requests merged in 2024-10, with the labels that each got.

#1441 Make language slug available via session metadata (formplayer branch)
  src/cli/java/org/commcare/util/screen/EntityScreen.java
  src/cli/java/org/commcare/util/screen/EntityScreenContext.java
  src/main/java/org/commcare/core/process/CommCareInstanceInitializer.java
  src/main/java/org/commcare/modern/session/SessionWrapper.java
  src/main/java/org/commcare/session/CommCareSession.java
  src/main/java/org/commcare/session/SessionInstanceBuilder.java
  src/main/java/org/javarosa/core/model/FormDef.java
  src/main/java/org/javarosa/core/model/instance/DataInstance.java
  src/main/java/org/javarosa/core/model/instance/ExternalDataInstance.java
  src/main/java/org/javarosa/core/model/instance/FormInstance.java
  src/main/java/org/javarosa/core/model/instance/InstanceInitializationFactory.java
  src/test/java/org/commcare/backend/suite/model/test/QueryModelTests.java
  src/test/java/org/commcare/test/utilities/TestInstanceInitializer.java
  src/test/java/org/javarosa/core/model/instance/test/DummyInstanceInitializationFactory.java
  src/translate/java/org/javarosa/engine/MockupProviderFactory.java
Labels: product/all-users

#1439 Fix case list search
  src/main/java/org/commcare/cases/entity/AsyncEntity.java
Labels: product/invisible

#1448 Fix menu instances Accumulation for menus with same ids
  src/main/java/org/commcare/session/CommCareSession.java
  src/test/java/org/commcare/backend/session/test/MenuTests.java
  src/test/resources/app_structure/suite.xml
Labels: bug
